apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginWordPress
spec:
  enabled: true
  version: 0.0.4
  requires: "*"
  author:
    name: wan92hen
    website: https://github.com/wan92hen
  logo: https://s.w.org/style/images/about/WordPress-logotype-wmark.png
  homepage: https://github.com/wan92hen/plugin-wordpress
  displayName: "WordPress导入"
  description: "支持从 WordPress 导出的 XML 文件导入数据"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-wordpress/blob/main/LICENSE"
